#############################################################################
# Makefile for building: SCL_Bind
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Tue Jul 19 22:46:16 2011
# Project:  SCL_Bind.pro
# Template: app
# Command: $(QMAKE) -o Makefile SCL_Bind.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I/usr/include/xsd -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -L/usr/lib -lxerces-c -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = SCL_Substation.hxx \
		SCL_IED.hxx \
		SCL_Enums.hxx \
		SCL_DataTypeTemplates.hxx \
		SCL_Communication.hxx \
		SCL_BaseTypes.hxx \
		SCL_BaseSimpleTypes.hxx \
		SCL.hxx
SOURCES = main.cpp \
		SCL_Substation.cxx \
		SCL_IED.cxx \
		SCL_Enums.cxx \
		SCL_DataTypeTemplates.cxx \
		SCL_Communication.cxx \
		SCL_BaseTypes.cxx \
		SCL_BaseSimpleTypes.cxx \
		SCL.cxx
OBJECTS = main.o \
		SCL_Substation.o \
		SCL_IED.o \
		SCL_Enums.o \
		SCL_DataTypeTemplates.o \
		SCL_Communication.o \
		SCL_BaseTypes.o \
		SCL_BaseSimpleTypes.o \
		SCL.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = SCL_Bind.pro
QMAKE_TARGET = SCL_Bind
DESTDIR  = 
TARGET   = SCL_Bind

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: SCL_Bind.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile SCL_Bind.pro
qmake: 
	@$(QMAKE) -o Makefile SCL_Bind.pro

dist: 
	@mkdir -p .tmp/SCL_Bind && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/SCL_Bind/ && ( cd `dirname .tmp/SCL_Bind` && $(TAR) SCL_Bind.tar SCL_Bind && $(GZIP) SCL_Bind.tar ) && $(MOVE) `dirname .tmp/SCL_Bind`/SCL_Bind.tar.gz . && $(DEL_FILE) -r .tmp/SCL_Bind

mocclean:

uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: main.cpp SCL.hxx \
		SCL_IED.hxx \
		SCL_Substation.hxx \
		SCL_Communication.hxx \
		SCL_DataTypeTemplates.hxx \
		SCL_BaseTypes.hxx \
		SCL_Enums.hxx \
		SCL_BaseSimpleTypes.hxx

SCL_Substation.o: SCL_Substation.cxx SCL_Substation.hxx \
		SCL_BaseTypes.hxx \
		SCL_Enums.hxx \
		SCL_BaseSimpleTypes.hxx

SCL_IED.o: SCL_IED.cxx SCL_IED.hxx \
		SCL_BaseTypes.hxx \
		SCL_Enums.hxx \
		SCL_BaseSimpleTypes.hxx

SCL_Enums.o: SCL_Enums.cxx SCL_Enums.hxx \
		SCL_BaseSimpleTypes.hxx

SCL_DataTypeTemplates.o: SCL_DataTypeTemplates.cxx SCL_DataTypeTemplates.hxx \
		SCL_BaseTypes.hxx \
		SCL_Enums.hxx \
		SCL_BaseSimpleTypes.hxx

SCL_Communication.o: SCL_Communication.cxx SCL_Communication.hxx \
		SCL_BaseTypes.hxx \
		SCL_Enums.hxx \
		SCL_BaseSimpleTypes.hxx

SCL_BaseTypes.o: SCL_BaseTypes.cxx SCL_BaseTypes.hxx \
		SCL_Enums.hxx \
		SCL_BaseSimpleTypes.hxx

SCL_BaseSimpleTypes.o: SCL_BaseSimpleTypes.cxx SCL_BaseSimpleTypes.hxx

SCL.o: SCL.cxx SCL.hxx \
		SCL_Substation.hxx \
		SCL_IED.hxx \
		SCL_Communication.hxx \
		SCL_DataTypeTemplates.hxx \
		SCL_BaseTypes.hxx \
		SCL_Enums.hxx \
		SCL_BaseSimpleTypes.hxx

####### Install

install:  

uninstall:  

